title: Branden in a Flash Developer Portfolio
email: Maxtheflash@yahoo.com
description: Coding the future, One line at a time
baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: "https://maxtheflash.github.io" 
twitter_username: Maxytheflash
github_username: maxtheflash

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

      
markdown: kramdown
permalink: pretty
